### ISSUE TITLE
 is this project open source?

### ISSUE THREAD

**Issue by iamqiz** [Tampermonkey/tampermonkey-editors#1]
I want to make contribution for example when click extension icon, it will not only open  https://vscode.dev/ but also open the usescript that being edited in tampermonkey settings page;

**Comment by derjanb** [comment]
Fixed by 27529b129ac077c3d51c7a3337810d5573d2e8d3

**Comment by iamqiz** [comment]
@derjanb thank you very much❤ ! you are awesome !
